name: driver_flutter
description: Driver app for ride-sharing


version: 3.25.0-0.1.pre

environment:
  sdk: ">=3.5.1 <4.0.0"
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: ^2.4.1
  web: ^1.0.0

  # Geo
  latlong2: ^0.9.0
  geolocator: ^13.0.1
  analyzer: ^6.0.0


  # Localization
  flutter_localizations:
    sdk: flutter
  intl: any

  # State management
  flutter_bloc: ^8.1.5
  hydrated_bloc: ^9.1.5

  # Dependency injection
  get_it: ^7.6.7
  injectable: ^2.4.1

  # Routing
  auto_route: ^9.2.2

  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_dotenv: ^5.1.0

  # Helpers
  dartz: ^0.10.1
  rxdart: ^0.27.7
  equatable: ^2.0.3
  path_provider: ^2.1.1
  json_annotation: ^4.8.1
  url_launcher: ^6.2.5
  connectivity_plus: ^6.0.1
  file_picker: ^8.0.0+1
  flutter_ringtone_player: ^4.0.0+3

  # Firebase
  firebase_analytics: ^11.3.0
  firebase_core: ^3.4.0
  firebase_crashlytics: ^4.0.4
  firebase_messaging: ^15.1.0

  # UI
  ionicons: 0.2.2
  flutter_rating_bar: ^4.0.1
  fl_chart: ^0.69.0
  dotted_border: ^2.1.0
  generic_map:
    path: ../../libs/generic_map
  flutter_common:
    path: ../../libs/flutter_common
  lottie: ^3.1.0
  cupertino_icons: ^1.0.8

  # Network
  graphql: ^5.2.0-beta.8
  cached_network_image: ^3.3.0
  collection: ^1.19.0
  dotted_line: ^3.2.2
  gauge_indicator: ^0.4.3
  map_launcher: ^3.5.0
  share_plus: ^10.0.2
  location: ^7.0.0
  package_info_plus: ^8.0.2
  maps_toolkit: ^3.0.0
  wakelock_plus: ^1.2.1
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1
  flutter_map: ^7.0.2


dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.12
  build_web_compilers: ^4.0.10
  flutter_gen_runner: ^5.4.0
  flutter_gen: ^5.4.0
  flutter_lints: ^4.0.0
  injectable_generator: ^2.6.2
  build_verify: ^3.1.0
  graphql_codegen: 0.14.0
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1

  flutter_test:
    sdk: flutter

dependency_overrides:
  web: ^0.5.1
  collection: ^1.18.0


flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - assets/images/
    - assets/avatars/
    - assets/lottie/
    - assets/countries/
    - assets/notification.mp3

  fonts:
    - family: GeneralSans
      fonts:
        - asset: assets/fonts/generalsansextralight.ttf
          weight: 200
        - asset: assets/fonts/generalsanslight.ttf
          weight: 300
        - asset: assets/fonts/generalsansregular.ttf
          weight: 400
        - asset: assets/fonts/generalsansmedium.ttf
          weight: 500
        - asset: assets/fonts/generalsanssemibold.ttf
          weight: 600
        - asset: assets/fonts/generalsansbold.ttf
          weight: 700

    - family: Inter
      fonts:
        - asset: assets/fonts/interthin.ttf
          weight: 100
        - asset: assets/fonts/interextralight.ttf
          weight: 200
        - asset: assets/fonts/interlight.ttf
          weight: 300
        - asset: assets/fonts/interregular.ttf
          weight: 400
        - asset: assets/fonts/intermedium.ttf
          weight: 500
        - asset: assets/fonts/intersemibold.ttf
          weight: 600
        - asset: assets/fonts/interbold.ttf
          weight: 700
        - asset: assets/fonts/interextrabold.ttf
          weight: 800
        - asset: assets/fonts/interblack.ttf
          weight: 900

flutter_gen:
  integrations:
    lottie: true
