name: Fortify AST Scan
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: 39 0 * * 6
  workflow_dispatch: null
jobs:
  Fortify-AST-Scan:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Check Out Source Code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - name: Run FoD SAST Scan
        uses: fortify/github-action@a92347297e02391b857e7015792cd1926a4cd418
        with:
          sast-scan: true
        env:
          FOD_URL: 'https://ams.fortify.com'
          FOD_TENANT: '${{secrets.FOD_TENANT}}'
          FOD_USER: '${{secrets.FOD_USER}}'
          FOD_PASSWORD: '${{secrets.FOD_PAT}}'
      - name: Cache
        uses: actions/cache@v4.0.2
        with:
          path: null
          key: null
          restore-keys: null
          upload-chunk-size: null
          enableCrossOsArchive: null
          fail-on-cache-miss: null
          lookup-only: null
          save-always: null
      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.2
        with: null
          java-version: null
          java-version-file: null
          distribution: null
          java-package: null
          architecture: null
          jdkFile: null
        check-latest: null
          server-id: null
        server-username: null
        server-password: null
        settings-path: null
        overwrite-settings: null
        gpg-private-key: null
        gpg-passphrase: null
        cache: null
        cache-dependency-path: null
        job-status: null
        token: null
        mvn-toolchain-id: null
        mvn-toolchain-vendor: null
      - name: Close Stale Issues
        uses: actions/stale@v9.0.0
        with: null
        repo-token: null
        stale-issue-message: null
        stale-pr-message: null
        close-issue-message: null
        close-pr-message: null
        days-before-stale: null
        days-before-issue-stale: null
        days-before-pr-stale: null
        days-before-close: null
        days-before-issue-close: null
        days-before-pr-close: null
        stale-issue-label: null
        close-issue-label: null
        exempt-issue-labels: null
        close-issue-reason: null
        stale-pr-label: null
        close-pr-label: null
        exempt-pr-labels: null
        exempt-milestones: null
        exempt-issue-milestones: null
        exempt-pr-milestones: null
        exempt-all-milestones: null
        exempt-all-issue-milestones: null
        exempt-all-pr-milestones: null
        only-labels: null
        any-of-labels: null
        any-of-issue-labels: null
        any-of-pr-labels: null
        only-issue-labels: null
        only-pr-labels: null
        operations-per-run: null
        remove-stale-when-updated: null
        remove-issue-stale-when-updated: null
        remove-pr-stale-when-updated: null
        debug-only: null
        ascending: null
        delete-branch: null
        start-date: null
        exempt-assignees: null
        exempt-issue-assignees: null
        exempt-pr-assignees: null
        exempt-all-assignees: null
        exempt-all-issue-assignees: null
        exempt-all-pr-assignees: null
        exempt-draft-pr: null
        enable-statistics: null
        labels-to-add-when-unstale: null
        labels-to-remove-when-stale: null
        labels-to-remove-when-unstale: null
        ignore-updates: null
        ignore-issue-updates: null
        ignore-pr-updates: null
        include-only-assigned: null
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.1
        with: null
        dotnet-version: null
        dotnet-quality: null
        global-json-file: null
        source-url: null
        owner: null
        config-file:
          cache: null
          cache-dependency-path: null
