name: SonarCloud analysis
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null
permissions:
  pull-requests: read
jobs:
  Analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Analyze with SonarCloud
        uses: >-
          SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
        env:
          SONAR_TOKEN: '${{ secrets.SONAR_TOKEN }}'
        with:
          args: '-Dsonar.projectKey= -Dsonar.organization='
          projectBaseDir: .
      - name: Cache
        uses: actions/cache@v4.0.2
        with:
          path: null
          key: null
          restore-keys: null
          upload-chunk-size: null
          enableCrossOsArchive: null
    fail-on-cache-miss: null
    lookup-only: null
    save-always: null
